services:
  - type: web
    name: vortex
    runtime: node
    plan: free
    buildCommand: npm install --production
    startCommand: node server/verify.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        sync: false

  - type: web
    name: vortex-panel
    runtime: node
    plan: free
    buildCommand: npm install --production
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: dadamoayu2-coder/vortex
